# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Github Pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - uses: crazy-max/ghaction-github-pages@v2.1.2
      with:
        fqdn: calc.sg
        build_dir: build
